# Generated by Django 4.2.1 on 2023-06-04 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='Attendance',
            field=models.BooleanField(default=False),
        ),
    ]
