# Generated by Django 4.2.1 on 2023-06-04 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userimage_created_at_userimage_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_city', models.CharField(blank=True, max_length=200, null=True)),
                ('Created_At', models.DateTimeField(auto_now_add=True, null=True)),
                ('Updated_At', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
