# Generated by Django 4.2.1 on 2023-06-04 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.location'),
        ),
    ]
