# Generated by Django 4.2.1 on 2023-06-04 07:01

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_profile_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userimage',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='PNG', keep_meta=True, quality=-1, scale=None, size=[500, 300], upload_to='user_images/'),
        ),
    ]
